// constants
const CONST_LOCAL_STORAGE_LOGGED_USER = 'loggedUser';
const CONST_MODULE_EMPLOYEES = 'EMPLOYEES';
const CONST_MODULE_DEPARTMENTS = 'DEPARTMENTS';
const CONST_PAGINATION_SIZE = 10;
const CONST_ACTION_ADD = 'ADD';
// CRUD
const CONST_GETALL = 'getAll';
const CONST_GET = 'get';
const CONST_POST = 'post';
const CONST_PUT = 'put';
const CONST_DELETE = 'delete';

//Form types
const CONST_TYPE_TEXT = 'text';
const CONST_TYPE_EMAIL = 'email';
// Form fieldTypes
const CONST_FIELD_INPUT = 'INPUT';
const CONST_FIELD_DATE_PICKER = 'DATE_PICKER';
const CONST_FIELD_RADIO = 'RADIO';
const CONST_FIELD_RADIO_GROUP = 'RADIO_GROUP';
const CONST_FIELD_CHECKBOX = 'CHECKBOX';
const CONST_FIELD_SELECT = 'SELECT';
const CONST_FIELD_MULTI_SELECT = 'MULTI_SELECT';

// Dialog open/close params
const CONST_MODULE_EMPLOYEES_MODAL = 'employeesModalOpen';
const CONST_APP_CONFIRM_MODAL = 'isConfirmModalOpen';
const CONST_APP_CONFIRM_MODAL_HANDLE = 'handleAppConfirmModal';

// Menus
const CONST_APP_MENU = 'isMoreMenuOpen';

// components
const COMP_CustomCard = 'CustomCard';

export { COMP_CustomCard };
export {
    CONST_LOCAL_STORAGE_LOGGED_USER,
    CONST_MODULE_EMPLOYEES,
    CONST_MODULE_DEPARTMENTS,
    CONST_PAGINATION_SIZE,
    CONST_ACTION_ADD,
    // Crud
    CONST_GETALL,
    CONST_GET,
    CONST_POST,
    CONST_PUT,
    CONST_DELETE,
    // Form types
    CONST_TYPE_TEXT,
    CONST_TYPE_EMAIL,
    // Form fieldTypes
    CONST_FIELD_INPUT,
    CONST_FIELD_DATE_PICKER,
    CONST_FIELD_RADIO_GROUP,
    CONST_FIELD_RADIO,
    CONST_FIELD_CHECKBOX,
    CONST_FIELD_SELECT,
    CONST_FIELD_MULTI_SELECT,
    // Modals
    CONST_MODULE_EMPLOYEES_MODAL,
    CONST_APP_CONFIRM_MODAL,
    CONST_APP_CONFIRM_MODAL_HANDLE,
    // Menu
    CONST_APP_MENU
};
